### ISSUE TITLE
Time Zone oddity

### ISSUE THREAD

**Issue by ruckc** [CaptainCodeman/time-display#1]
I'm using <time-diff></time-diff>.  The timestamps are in ISO 8601 format, example 2016-09-13T23:40:25.463Z.  When I put this time into <time-diff datetime="2016-09-13T23:40:25.463Z"></time-diff> it renders as "in 4 hours" which is my current UTC offset.  It appears it isn't calculating the timezone offset correctly.

**Comment by ruckc** [comment]
Looks like the appropriate solution is the expose a parseFormat property and use it in the fecha.parse();

**Comment by CaptainCodeman** [comment]
Just to check I understand correctly: you put the _current_ ISO 8601 format timestamp in and at that time it's not saying "just now" as it should, it's telling you the difference between that UTC time and your local time (the timezone offset). Is that right? What browser is that with?

**Comment by ruckc** [comment]
I put a recent ISO 8601 timestamp, within 30 minutes or so.  Chrome browser.  I think its something to do with your hardcoded fecha.parse format, and the fact that as I dug further in [fecha isn't intended](https://github.com/taylorhakes/fecha/issues/6#issuecomment-138104161) for natively support Date.parse ISO 8601 formats.

**Comment by CaptainCodeman** [comment]
Thanks for spotting this - using the native Date parsing seems to do the trick and should be safe (as long as the datetime is an ISO 8601 string as expected)
